version: "3.9"
services:
  petrabot:
    image: kamenka/petrabot:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 4096M
          cpus: '8.0'
        reservations:
          cpus: '2.0'
          memory: 512M
      placement:
        constraints:
          - "node.hostname==xubuntu-2"
      restart_policy:
        condition: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./videos:/app/videos
      - ./frames:/app/frames
      - ./db:/app/db
    environment:
      - PETRABOT_IMAGE_ID
      - PYTHONUNBUFFERED=1
