version: "3.9"
services:
  petrabot:
    image: kamenka/petrabot:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 4096M
          cpus: '8.0'
        reservations:
          cpus: '2.0'
          memory: 512M
      placement:
        constraints:
          - "node.hostname==xubuntu-2"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
